testing

diff --git a/actions/deployTerraform/action.yml b/actions/deployTerraform/action.yml
--- a/actions/deployTerraform/action.yml
+++ b/actions/deployTerraform/action.yml
@@ -107,11 +107,11 @@ runs:
     #   id: fmt
     #   run: terraform fmt -check
 
-    - name: Terraform Init
-      shell: bash
-      working-directory: ./deploy/terraform
-      id: init
-      run: terraform init --backend-config=backend.tfvars
+    # - name: Terraform Init
+    #   shell: bash
+    #   working-directory: ./deploy/terraform
+    #   id: init
+    #   run: terraform init --backend-config=backend.tfvars
 
     # - name: Composite Action 1
     #   uses: ./actions/greet
@@ -119,73 +119,73 @@ runs:
     #   with:
     #     who-to-greet: 'Mohamed'
 
-    - name: Terraform Validate
-      shell: bash
-      working-directory: ./deploy/terraform
-      id: validate
-      run: terraform validate -no-color
-
-    - name: Terraform Plan
-      shell: bash
-      working-directory: ./deploy/terraform
-      id: plan
-      if: github.event_name == 'pull_request'
-      run: terraform plan --var "environment=${{inputs.ENVIRONMENT}}" -no-color -input=false
-      continue-on-error: true
-
-    - uses: actions/github-script@v6
-      if: github.event_name == 'pull_request'
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      with:
-        github-token: ${{ inputs.GITHUB_TOKEN }}
-        script: |
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-
-          <details><summary>Show Plan</summary>
-
-          \`\`\`\n
-          ${process.env.PLAN}
-          \`\`\`
-
-          </details>
-
-          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-
-          github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
-
-    - name: Terraform Plan Status
-      shell: bash
-      working-directory: ./deploy/terraform
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
-
-    - name: Terraform Apply
-      shell: bash
-      working-directory: ./deploy/terraform
-      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-      run: terraform apply --var "environment=${{inputs.ENVIRONMENT}}" -auto-approve -input=false
-
-    # - name: Install Go
-    #   uses: actions/setup-go@v3
-    #   with: 
-    #     go-version: "1.14.1"
-
-    # - name: Run Tests
-    #   working-directory: ./deploy/test
+    # - name: Terraform Validate
     #   shell: bash
-    #   run: go test -v -timeout 8000s ./test.go 2>&1 | go-junit-report >test.xml
-      
-    # - uses: actions/upload-artifact@v3
-    #   if: always()
+    #   working-directory: ./deploy/terraform
+    #   id: validate
+    #   run: terraform validate -no-color
+
+    # - name: Terraform Plan
+    #   shell: bash
+    #   working-directory: ./deploy/terraform
+    #   id: plan
+    #   if: github.event_name == 'pull_request'
+    #   run: terraform plan --var "environment=${{inputs.ENVIRONMENT}}" -no-color -input=false
+    #   continue-on-error: true
+
+    # - uses: actions/github-script@v6
+    #   if: github.event_name == 'pull_request'
+    #   env:
+    #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
     #   with:
-    #     name: Test results
-    #     path: .deploy/test/*.xml
+    #     github-token: ${{ inputs.GITHUB_TOKEN }}
+    #     script: |
+    #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+    #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+    #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+    #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+
+    #       <details><summary>Show Plan</summary>
+
+    #       \`\`\`\n
+    #       ${process.env.PLAN}
+    #       \`\`\`
+
+    #       </details>
+
+    #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+    #       github.rest.issues.createComment({
+    #         issue_number: context.issue.number,
+    #         owner: context.repo.owner,
+    #         repo: context.repo.repo,
+    #         body: output
+    #       })
+
+    # - name: Terraform Plan Status
+    #   shell: bash
+    #   working-directory: ./deploy/terraform
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
+
+    # - name: Terraform Apply
+    #   shell: bash
+    #   working-directory: ./deploy/terraform
+    #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+    #   run: terraform apply --var "environment=${{inputs.ENVIRONMENT}}" -auto-approve -input=false
+
+    - name: Install Go
+      uses: actions/setup-go@v3
+      with: 
+        go-version: "1.14.1"
+
+    - name: Run Tests
+      working-directory: ./deploy/test
+      shell: bash
+      run: go test -v -timeout 8000s ./test.go 2>&1 | go-junit-report >test.xml
+      
+    - uses: actions/upload-artifact@v3
+      if: always()
+      with:
+        name: Test results
+        path: .deploy/test/*.xml
